### ISSUE TITLE
Feature: Show the calculated width/height based on the selected ratios

### ISSUE THREAD

**Issue by ghostsquad** [Tropfchen/ComfyUI-yaResolutionSelector#2]
I'd like to know what the calculated width/height actually is based on the selected ratios. Current work around is to pipe the integer to a "integer to text" node, and then a "show text" node. But this only shows the result after the image has been generated.

**Comment by Tropfchen** [comment]
If you are aware of any, providing an example of a node that displays and updates information without queuing a prompt would be very helpful.

**Comment by ghostsquad** [comment]
I think nodes that are client side only can do that (aka written in JavaScript). Rgthree has several client-side nodes IIRC
